apiVersion: v1
kind: Pod
metadata:
  name: magic-pod
  labels:
    name: magic-pod
    app: magic-app
spec:
  containers:
    - name: magic-pod
      image: fabiolrodriguez/magic-hello:latest
      ports:
        - containerPort: 8080