apiVersion: v1
kind: Service
metadata:
  name: magic-pod
  labels:
    name: magic-pod
    app: magic-app
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    name: magic-pod
    app: magic-app